version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 0
  - package-ecosystem: gradle
    directory: "/buildSrc"
    schedule:
      interval: daily
      time: "00:00"
    open-pull-requests-limit: 0
