# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Continuous Integration

on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
    branches-ignore:
      - gh-pages
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Build

    strategy:
      matrix:
        build-type: [DEBUG, RELEASE]
        update: [false, true]
    
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      UPDATE: ${{ matrix.update }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build --stacktrace

  validation:
    name: Validation
    
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
        with:
          allow-snapshots: true
